### ISSUE TITLE
Add time indication

### ISSUE THREAD

**Issue by barboaz** [yuvadm/geshem#7]
and keep it synced with the slider

**Comment by yuvadm** [comment]
Yeah I've been getting this request a lot. I have the code somewhere, just need to merge it.

Regardless, how's your react-foo? :wink:

**Comment by barboaz** [comment]
React is still banned from the Segmanta codebase... (:

**Comment by yuvadm** [comment]
What happened to "move fast, break shit"?

**Comment by barboaz** [comment]
We're afraid of hurting Angular's feelings

**Comment by yuvadm** [comment]
Fixed in new Vue.js-based version

**Comment by barboaz** [comment]
Woohoo! Right on time for the coming winter! 👍
